#!/usr/bin/env bash

mode="Default"
hyprctl monitors -j | jaq -rc --arg MODE "$mode" '.[] | select(.focused == true) | { id:.id, mode:$MODE }' 2>/dev/null
function handle {
  if [[ ${1:0:10} == "focusedmon" || ${1:0:6} == "submap" ]]; then
      if [[ ${1:0:6} == "submap" ]]; then
          mode="${1#*>>}"
          if [[ -z "${mode}" ]]; then
              mode="Normal"
          fi
      fi
      hyprctl monitors -j | jaq -rc --arg MODE "$mode" '.[] | select(.focused == true) | { id:.id, mode:$MODE }' 2>/dev/null
  fi

}

socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read line; do handle $line; done
