#!/bin/bash

pid_file="/tmp/hypr/swayidle.pid"

# Set the appropriate icon based on the existence of the PID file
if [ -f "$pid_file" ]
then
    icon=""
else
	icon=""
fi

off() {
	hypridle &
    echo $! > "$pid_file"
    notify-send "Inhibitor" "Deactivated" -i "$HOME/.config/eww/images/notification.png"
    eww update inhibitor=$icon
}

on() {
    pkill -F "$pid_file"
    rm -f "$pid_file"

    notify-send "Inhibitor" "Activated" -i "$HOME/.config/eww/images/notification.png"
    eww update inhibitor=$icon
}

toggle() {
    if [ -f "$pid_file" ]
    then
        on
    else
        off
    fi
}

case $1 in
    "toggle")
        toggle
        ;;
    "off")
        off
        ;;
    "on")
        on
        ;;
    *)
        echo $icon
        ;;
esac
