#!/bin/bash

pid_file="/tmp/hypr/swayidle.pid"

# Set the appropriate icon based on the existence of the PID file
if [ -f "$pid_file" ]
then
    icon=""
else
    icon=""
fi

off() {
    swayidle -w \
             timeout 275 'notify-send "Inhibitor" "Screen Off in 15 Sec"'\
             timeout 300 'swaylock-fancy &' \
             timeout 600 'hyprctl dispatch dpms off' \
             resume 'hyprctl dispatch dpms on' \
             before-sleep 'swaylock-fancy' &

    echo $! > "$pid_file"
    # TODO don't require full path
    notify-send "Inhibitor" "Deactivated" -i "/home/nehrbash/.config/eww/images/notification.png" 
    eww update inhibitor=$icon
}

on() {
    pkill -F "$pid_file"
    rm -f "$pid_file"

    notify-send "Inhibitor" "Activated" -i "/home/nehrbash/.config/eww/images/notification.png" 
    eww update inhibitor=$icon
}

toggle() {
    if [ -f "$pid_file" ]
    then
        on
    else
        off
    fi
}

case $1 in
    "toggle")
        toggle
        ;;
    "off")
        off
        ;;
    "on")
        on
        ;;
    *)
        echo $icon
        ;;
esac
