#!/bin/bash

emtime=$(emacsclient -e '(snehrbass/org-pomodoro-time)' 2> /dev/null)
pomoPercent=0
min=0
sec=0
if [ -z "${emtime}" ];
then
    emtime=0
else
    emtime=$(echo $emtime | cut -d '"' -f 2)
    min=$(bc <<< "$emtime/60")
    sec=$(bc <<< "$emtime%60")

    pomoTime=$(printf "%02d:%02d" $min $sec)
    pomoPercent=$(bc <<< "$emtime*100/1500") # 25 min cycle
fi

emtask=$(emacsclient -e '(snehrbass/org-pomodoro-task)' 2> /dev/null)

if [ -z "${emtask}" ];
then
   emtask="No Active Pomodoro"
   pomoTime="00:00"
else
   emtask=$(echo $emtask | cut -d '"' -f 2)
fi

if [[  "$min" == "0" ]]; then
    emsg="${emtask}"
else
    emsg="${min} min - ${emtask}"
fi

# if break is in the name trigger eww break splash screen
if [[ "$emtask" == *"Break"* ]]; then
    eww open-many pomo-break pomo-break2 2> dev/null
    sleep 15
fi


echo "{\"percent\": \"${pomoPercent}\", \"time\": \"${pomoTime}\", \"task\": \"${emtask}\", \"summary\": \"${emsg}\" }"
