#!/bin/bash

csv=$(emacs -batch -l ~/.emacs.d/early-init.el -eval '(org-batch-agenda-csv "t" org-agenda-files (quote ("~/doc/inbox.org" "~/doc/projects.org" "~/doc/repeater.org")) org-todo-keywords (quote ((sequence "TODO(t)" "NEXT(n/!)" "INPROGRESS(i/!)" "|" "DONE(d!/!)") (sequence "PROJECT(p)" "|" "DONE(d!/!)" "CANCELLED(c@/!)")(sequence "WAITING(w@/!)" "DELEGATED(e!)" "HOLD(h)" "|" "CANCELLED(c@/!)"))))')

# echo "$csv"
echo "$csv" | jq -Rsnc '
  {"tasks":
    [inputs
     | . / "\n"
     | (.[] | select(length > 0) | . / ",") as $input
     | select($input | length > 0)
     | {"title": $input[1], "state": $input[3]}] }
  | {
     "tasks": (.tasks[:8]),
     "num-total": ( [ .tasks[] | select( .state != "PROJECT")] | length),
     "num-tasks":  ( [ .tasks[:8][] | select( .state != "PROJECT")] | length)
  }'
