#+TITLE: Charybdis 3x5 Wireless — ZMK Firmware
#+PROPERTY: header-args :mkdirp yes
#+STARTUP: overview

Literate ZMK configuration for a wireless [[https://bastardkb.com/charybdis/][Bastard Keyboards Charybdis 3x5]]
(clone variant) with SuperMini nRF52840 controllers and PMW3610 trackball sensor.

Tangle this file with =C-c C-v t= to generate all ZMK config files
directly into =~/src/zmk-charybdis/=, then run =files/zmk/setup.sh= to
install the SDK and initialize west.

* Hardware

| Component     | Value                                      |
|---------------+--------------------------------------------|
| Keyboard      | Charybdis 3x5 (wireless split + trackball) |
| Controllers   | SuperMini nRF52840 (nice!nano v2 compat)   |
| Sensor        | PMW3610 (PMW3360-based PCB, low-power)     |
| Keys          | 3×5 + 3 left thumbs + 2 right thumbs (35)  |
| Communication | BLE between halves, BLE/USB to host        |

** Pin Mapping

Bastard KB Charybdis PCB uses Splinktegrated-compatible wiring.
The 3x5 variant uses rows R1-R4 and columns C1-C5 from the
Splinktegrated pinout:

| Function | Splinktegrated GPIO | pro_micro pin |
|----------+---------------------+---------------|
| Row 0    | GP29 (R1)           |            21 |
| Row 1    | GP26 (R2)           |            18 |
| Row 2    | GP5 (R3)            |             5 |
| Row 3    | GP4 (R4)            |             4 |
| Col 0    | GP27 (C1)           |            19 |
| Col 1    | GP28 (C2)           |            20 |
| Col 2    | GP21 (C3)           |            10 |
| Col 3    | GP6 (C4)            |             6 |
| Col 4    | GP7 (C5)            |             7 |

Right half columns are reversed (mirrored PCB).

* Setup
** Guix Profile

All build dependencies as a Guix manifest.

#+BEGIN_SRC scheme :tangle ~/src/zmk-charybdis/guix-manifest.scm
(use-modules (gnu packages))

(specifications->manifest
 '(;; Build system
   "cmake" "ninja" "dtc" "gcc-toolchain" "wget"
   ;; Zephyr / West
   "west" "python" "python-pyelftools"))
#+END_SRC

** West Manifest

Tells =west= where to fetch ZMK and the PMW3610 trackball driver.

#+BEGIN_SRC yaml :tangle ~/src/zmk-charybdis/config/west.yml
manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: 280Zo
      url-base: https://github.com/280Zo

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: 280Zo
      revision: main

  self:
    path: config
#+END_SRC

** Build Matrix

#+BEGIN_SRC yaml :tangle ~/src/zmk-charybdis/build.yaml
---
include:
  - board: nice_nano
    shield: charybdis_left_bt
  - board: nice_nano
    shield: charybdis_right_bt
  - board: nice_nano
    shield: settings_reset
#+END_SRC

** Setup Script

Run =./files/zmk/setup.sh= after tangling. It installs the Zephyr SDK
if missing, runs =west init= / =west update= if first time, and drops
you into a Guix shell ready to build.

#+BEGIN_SRC sh :tangle setup.sh :shebang "#!/bin/sh"
set -e

WORKSPACE="$HOME/src/zmk-charybdis"
ZEPHYR_SDK_VERSION="0.17.0"
ZEPHYR_SDK_INSTALL_DIR="$HOME/.local/zephyr-sdk-${ZEPHYR_SDK_VERSION}"

# Install Zephyr SDK if missing
if [ ! -d "$ZEPHYR_SDK_INSTALL_DIR" ]; then
    echo "Installing Zephyr SDK ${ZEPHYR_SDK_VERSION}..."
    SDK_URL="https://github.com/zephyrproject-rtos/sdk-ng/releases/download"
    SDK_FILE="zephyr-sdk-${ZEPHYR_SDK_VERSION}_linux-x86_64_minimal.tar.xz"
    wget -q "${SDK_URL}/v${ZEPHYR_SDK_VERSION}/${SDK_FILE}" -O "/tmp/${SDK_FILE}"
    tar xf "/tmp/${SDK_FILE}" -C "$HOME/.local/"
    "$ZEPHYR_SDK_INSTALL_DIR/setup.sh" -t arm-zephyr-eabi
    rm "/tmp/${SDK_FILE}"
    echo "Zephyr SDK installed to $ZEPHYR_SDK_INSTALL_DIR"
fi

# Enter Guix shell from workspace dir
cd "$WORKSPACE"
exec guix shell -m guix-manifest.scm -- sh -c '
    export ZEPHYR_SDK_INSTALL_DIR="'"$ZEPHYR_SDK_INSTALL_DIR"'"
    export ZEPHYR_BASE="$PWD/zephyr"
    export CMAKE_PREFIX_PATH="$PWD/zephyr/share/zephyr-package/cmake"
    unset C_INCLUDE_PATH CPLUS_INCLUDE_PATH LIBRARY_PATH
    if [ ! -d zmk ]; then
        echo "Initializing west workspace..."
        west init -l config
        west update
    fi
    echo "Ready. Build with:"
    echo "  west build -s zmk/app -b nice_nano -- -DSHIELD=charybdis_left_bt -DZMK_CONFIG=\$(pwd)/config"
    exec "$SHELL"
'
#+END_SRC

* Shield Configuration
** Shared (dtsi)

The Charybdis 3x5 matrix: 4 rows × 5 cols per half (row 3 = thumb row).

#+BEGIN_SRC dts :tangle ~/src/zmk-charybdis/config/boards/shields/charybdis/charybdis.dtsi
#include <dt-bindings/zmk/matrix_transform.h>

/ {
    chosen {
        zmk,kscan = &kscan0;
        zmk,matrix-transform = &default_transform;
    };

    default_transform: keymap_transform_0 {
        compatible = "zmk,matrix-transform";
        columns = <10>;
        rows = <4>;
        // 3x5 + 3 left thumbs + 2 right thumbs = 35 keys
        map = <
            RC(0,0) RC(0,1) RC(0,2) RC(0,3) RC(0,4)   RC(0,5) RC(0,6) RC(0,7) RC(0,8) RC(0,9)
            RC(1,0) RC(1,1) RC(1,2) RC(1,3) RC(1,4)   RC(1,5) RC(1,6) RC(1,7) RC(1,8) RC(1,9)
            RC(2,0) RC(2,1) RC(2,2) RC(2,3) RC(2,4)   RC(2,5) RC(2,6) RC(2,7) RC(2,8) RC(2,9)
                            RC(3,2) RC(3,3) RC(3,4)   RC(3,5) RC(3,6)
        >;
    };

    kscan0: kscan {
        compatible = "zmk,kscan-gpio-matrix";
        wakeup-source;
    };
};
#+END_SRC

** Left Half (Central)

#+BEGIN_SRC dts :tangle ~/src/zmk-charybdis/config/boards/shields/charybdis/charybdis_left_bt.overlay
#include "charybdis.dtsi"

&kscan0 {
    col-gpios
        = <&pro_micro 19 (GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)>
        , <&pro_micro 20 (GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)>
        , <&pro_micro 10 (GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)>
        , <&pro_micro 6 (GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)>
        , <&pro_micro 7 (GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)>
        ;

    row-gpios
        = <&pro_micro 21 GPIO_ACTIVE_HIGH>
        , <&pro_micro 18 GPIO_ACTIVE_HIGH>
        , <&pro_micro 5 GPIO_ACTIVE_HIGH>
        , <&pro_micro 4 GPIO_ACTIVE_HIGH>
        ;
};

/ {
    split_inputs {
        #address-cells = <1>;
        #size-cells = <0>;

        trackball_split: trackball_split@0 {
            compatible = "zmk,input-split";
            reg = <0>;
        };
    };

    trackball_listener: trackball_listener {
        compatible = "zmk,input-listener";
        device = <&trackball_split>;
    };
};
#+END_SRC

** Right Half (Peripheral + Trackball)

Column GPIOs are reversed (mirrored PCB).

#+BEGIN_SRC dts :tangle ~/src/zmk-charybdis/config/boards/shields/charybdis/charybdis_right_bt.overlay
#include "charybdis.dtsi"
#include <zephyr/dt-bindings/input/input-event-codes.h>

&default_transform {
    col-offset = <5>;
};

&kscan0 {
    col-gpios
        = <&pro_micro 7 (GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)>
        , <&pro_micro 6 (GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)>
        , <&pro_micro 10 (GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)>
        , <&pro_micro 20 (GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)>
        , <&pro_micro 19 (GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)>
        ;

    row-gpios
        = <&pro_micro 21 GPIO_ACTIVE_HIGH>
        , <&pro_micro 18 GPIO_ACTIVE_HIGH>
        , <&pro_micro 5 GPIO_ACTIVE_HIGH>
        , <&pro_micro 4 GPIO_ACTIVE_HIGH>
        ;
};

// Trackball sensor on right half SPI bus
&pinctrl {
    spi0_default: spi0_default {
        group1 {
            psels = <NRF_PSEL(SPIM_SCK, 0, 8)>,
                <NRF_PSEL(SPIM_MOSI, 0, 17)>,
                <NRF_PSEL(SPIM_MISO, 0, 17)>;
        };
    };

    spi0_sleep: spi0_sleep {
        group1 {
            psels = <NRF_PSEL(SPIM_SCK, 0, 8)>,
                <NRF_PSEL(SPIM_MOSI, 0, 17)>,
                <NRF_PSEL(SPIM_MISO, 0, 17)>;
            low-power-enable;
        };
    };
};

&spi0 {
    status = "okay";
    compatible = "nordic,nrf-spim";
    pinctrl-0 = <&spi0_default>;
    pinctrl-1 = <&spi0_sleep>;
    pinctrl-names = "default", "sleep";
    cs-gpios = <&gpio0 20 GPIO_ACTIVE_LOW>;

    trackball: trackball@0 {
        status = "okay";
        compatible = "pixart,pmw3610-alt";
        reg = <0>;
        spi-max-frequency = <2000000>;
        irq-gpios = <&gpio0 6 (GPIO_ACTIVE_LOW | GPIO_PULL_UP)>;
        cpi = <800>;
        evt-type = <INPUT_EV_REL>;
        x-input-code = <INPUT_REL_X>;
        y-input-code = <INPUT_REL_Y>;
        swap-xy;
        invert-x;
        invert-y;
        force-awake;
        force-awake-4ms-mode;
    };
};

/ {
    split_inputs {
        #address-cells = <1>;
        #size-cells = <0>;

        trackball_split: trackball_split@0 {
            compatible = "zmk,input-split";
            reg = <0>;
            device = <&trackball>;
        };
    };

    trackball_listener {
        compatible = "zmk,input-listener";
        device = <&trackball>;
    };
};
#+END_SRC

** Kconfig

#+BEGIN_SRC conf :tangle ~/src/zmk-charybdis/config/boards/shields/charybdis/Kconfig.shield
config SHIELD_CHARYBDIS_LEFT_BT
    def_bool $(shields_list_contains,charybdis_left_bt)

config SHIELD_CHARYBDIS_RIGHT_BT
    def_bool $(shields_list_contains,charybdis_right_bt)
#+END_SRC

#+BEGIN_SRC conf :tangle ~/src/zmk-charybdis/config/boards/shields/charybdis/Kconfig.defconfig
if SHIELD_CHARYBDIS_LEFT_BT

config ZMK_KEYBOARD_NAME
    default "Charybdis"

config ZMK_SPLIT_ROLE_CENTRAL
    default y

endif # SHIELD_CHARYBDIS_LEFT_BT

if SHIELD_CHARYBDIS_LEFT_BT || SHIELD_CHARYBDIS_RIGHT_BT

config ZMK_SPLIT
    default y

endif
#+END_SRC

#+BEGIN_SRC conf :tangle ~/src/zmk-charybdis/config/charybdis.conf
# General
CONFIG_ZMK_KEYBOARD_NAME="Charybdis"
CONFIG_ZMK_USB=y

# Wireless
CONFIG_BT=y
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5
CONFIG_ZMK_BLE=y
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y

# Pointing / trackball
CONFIG_ZMK_MOUSE=y
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_PMW3610_ALT=y

# Power
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=600000
CONFIG_ZMK_EXT_POWER=y

# Debounce
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=2
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5
#+END_SRC

* Keymap
** Includes and Defines

#+BEGIN_SRC dts :tangle ~/src/zmk-charybdis/config/charybdis.keymap
#include <behaviors.dtsi>
#include <dt-bindings/zmk/keys.h>
#include <dt-bindings/zmk/bt.h>
#include <dt-bindings/zmk/mouse.h>
#include <dt-bindings/zmk/outputs.h>
#include <behaviors/mouse_keys.dtsi>
#include <dt-bindings/zmk/ext_power.h>

#define BASE   0
#define NAV    1
#define POINT  2
#define MEDIA  3
#define NUM    4
#define SYM    5
#define FN     6
#define SCROLL 7
#+END_SRC

** Home Row Mods

Balanced hold-tap for home row modifiers. Tuned for Colemak-DH:
- Positional: left mods only trigger on right-hand keys and vice versa
- 280ms tapping-term, require-prior-idle prevents accidental mods during fast typing

#+BEGIN_SRC dts :tangle ~/src/zmk-charybdis/config/charybdis.keymap
/ {
    behaviors {
        hml: home_row_mod_left {
            compatible = "zmk,behavior-hold-tap";
            #binding-cells = <2>;
            flavor = "balanced";
            tapping-term-ms = <280>;
            require-prior-idle-ms = <150>;
            quick-tap-ms = <175>;
            bindings = <&kp>, <&kp>;
            hold-trigger-key-positions = <
                5  6  7  8  9        /* top right */
                15 16 17 18 19       /* home right */
                25 26 27 28 29       /* bottom right */
                33 34                /* right thumbs */
            >;
            hold-trigger-on-release;
        };

        hmr: home_row_mod_right {
            compatible = "zmk,behavior-hold-tap";
            #binding-cells = <2>;
            flavor = "balanced";
            tapping-term-ms = <280>;
            require-prior-idle-ms = <150>;
            quick-tap-ms = <175>;
            bindings = <&kp>, <&kp>;
            hold-trigger-key-positions = <
                0  1  2  3  4        /* top left */
                10 11 12 13 14       /* home left */
                20 21 22 23 24       /* bottom left */
                30 31 32             /* left thumbs */
            >;
            hold-trigger-on-release;
        };
        ltr: layer_tap_repeat {
            compatible = "zmk,behavior-hold-tap";
            #binding-cells = <2>;
            flavor = "balanced";
            tapping-term-ms = <200>;
            quick-tap-ms = <175>;
            bindings = <&mo>, <&kp>;
        };
    }; /* end behaviors */
#+END_SRC

** Combos

Fn layer via right thumb combo (Enter + Backspace simultaneously).

#+BEGIN_SRC dts :tangle ~/src/zmk-charybdis/config/charybdis.keymap
combos {
    compatible = "zmk,combos";

    combo_fn {
        timeout-ms = <50>;
        key-positions = <33 34>;  /* right inner + right outer thumb */
        bindings = <&mo FN>;
    };
};
#+END_SRC

** Layers
*** Base — Colemak-DH

#+NAME: base-layer
| Q          | W          | F          | P          | B   | J   | L          | U          | Y          | '          |
| GUI / A    | ALT / R    | CTL / S    | SFT / T    | G   | M   | SFT / N    | CTL / E    | ALT / I    | GUI / O    |
| Z          | RALT / X   | C          | D          | V   | K   | H          | ,          | RALT / .   | /          |
|            |            | ESC / MEDIA | SPC / NAV  | TAB / POINT | ENT / SYM | BSPC / NUM |            |            |

#+BEGIN_SRC dts :tangle ~/src/zmk-charybdis/config/charybdis.keymap
    keymap {
        compatible = "zmk,keymap";

        base_layer {
            display-name = "Base";
            bindings = <
                &kp Q       &kp W       &kp F        &kp P        &kp B          &kp J   &kp L        &kp U        &kp Y       &kp APOS
                &hml LGUI A &hml LALT R &hml LCTRL S &hml LSHFT T &kp G          &kp M   &hmr RSHFT N &hmr RCTRL E &hmr LALT I &hmr RGUI O
                &kp Z       &hml RALT X &kp C        &kp D        &kp V          &kp K   &kp H        &kp COMMA    &hmr RALT DOT &kp FSLH
                                         &lt MEDIA ESC &ltr NAV SPACE &lt POINT TAB   &lt SYM ENTER &ltr NUM BSPC
            >;
        };
#+END_SRC

*** Nav — Navigation + Editing

#+BEGIN_SRC dts :tangle ~/src/zmk-charybdis/config/charybdis.keymap
        nav_layer {
            display-name = "Nav";
            bindings = <
                &to 0 &none    &none     &none     &none       &kp K_REDO &kp K_UNDO &kp K_CUT  &kp K_COPY  &kp K_PASTE
                &kp LGUI &kp LALT &kp LCTRL &kp LSHFT &none       &kp CAPS   &kp LEFT   &kp DOWN   &kp UP      &kp RIGHT
                &none    &kp RALT &none     &none     &none       &kp INS    &kp HOME   &kp PG_DN  &kp PG_UP   &kp END
                                   &none     &trans    &none       &kp ENTER  &kp BSPC
            >;
        };
#+END_SRC

*** Pointer — Trackball Controls

#+BEGIN_SRC dts :tangle ~/src/zmk-charybdis/config/charybdis.keymap
        pointer_layer {
            display-name = "Point";
            bindings = <
                &to 0    &none    &none     &none     &none       &none      &none      &none      &none     &none
                &kp LGUI &kp LALT &kp LCTRL &kp LSHFT &none       &none      &mkp LCLK  &mkp MCLK  &mkp RCLK &none
                &none    &kp RALT &none     &none     &none       &none      &mo SCROLL &none      &none     &none
                                   &trans    &mkp LCLK &mo SCROLL  &kp PG_UP  &kp PG_DN
            >;
        };
#+END_SRC

*** Scroll — Trackball Scroll Mode

#+BEGIN_SRC dts :tangle ~/src/zmk-charybdis/config/charybdis.keymap
        scroll_layer {
            display-name = "Scroll";
            bindings = <
                &to 0    &none    &none     &none     &none       &none      &none      &none      &none     &none
                &kp LGUI &kp LALT &kp LCTRL &kp LSHFT &none       &none      &mkp LCLK  &mkp MCLK  &mkp RCLK &none
                &none    &kp RALT &none     &none     &none       &none      &trans     &none      &none     &none
                                   &trans    &mkp LCLK &trans      &kp PG_UP  &kp PG_DN
            >;
        };
#+END_SRC

*** Media — Volume, Playback, Bluetooth

#+BEGIN_SRC dts :tangle ~/src/zmk-charybdis/config/charybdis.keymap
        media_layer {
            display-name = "Media";
            bindings = <
                &to 0 &none    &none     &none     &none       &none        &none      &none        &none        &none
                &kp LGUI &kp LALT &kp LCTRL &kp LSHFT &none       &none        &kp C_PREV &kp C_VOL_DN &kp C_VOL_UP &kp C_NEXT
                &none    &kp RALT &none     &none     &none       &bt BT_SEL 0 &bt BT_SEL 1 &bt BT_SEL 2 &bt BT_SEL 3 &bt BT_CLR
                                   &trans    &none     &none       &kp C_STOP   &kp C_PP
            >;
        };
#+END_SRC

*** Num — Number Pad

#+BEGIN_SRC dts :tangle ~/src/zmk-charybdis/config/charybdis.keymap
        num_layer {
            display-name = "Num";
            bindings = <
                &kp LBKT  &kp N7 &kp N8  &kp N9 &kp RBKT       &none  &none     &none     &none    &to 0
                &kp SEMI  &kp N4 &kp N5  &kp N6 &kp EQUAL      &none  &kp RSHFT &kp RCTRL &kp LALT &kp RGUI
                &kp GRAVE &kp N1 &kp N2  &kp N3 &kp BSLH       &none  &none     &none     &kp RALT &none
                                  &kp DOT &kp N0 &kp MINUS      &none  &trans
            >;
        };
#+END_SRC

*** Sym — Symbols

#+BEGIN_SRC dts :tangle ~/src/zmk-charybdis/config/charybdis.keymap
        sym_layer {
            display-name = "Sym";
            bindings = <
                &kp LBRC  &kp AMPS &kp ASTRK  &kp LPAR  &kp RBRC       &none  &none     &none     &none    &to 0
                &kp COLON &kp DLLR &kp PRCNT &kp CARET &kp PLUS       &none  &kp RSHFT &kp RCTRL &kp LALT &kp RGUI
                &kp TILDE &kp EXCL &kp AT    &kp HASH  &kp PIPE       &none  &none     &none     &kp RALT &none
                                    &kp LPAR  &kp RPAR  &kp UNDER      &trans &none
            >;
        };
#+END_SRC

*** Fn — Function Keys (via combo: Enter + Backspace)

#+BEGIN_SRC dts :tangle ~/src/zmk-charybdis/config/charybdis.keymap
        fn_layer {
            display-name = "Fn";
            bindings = <
                &kp F12 &kp F7 &kp F8  &kp F9    &kp PSCRN      &none  &none     &none     &none    &to 0
                &kp F11 &kp F4 &kp F5  &kp F6    &kp SLCK       &none  &kp RSHFT &kp RCTRL &kp LALT &kp RGUI
                &kp F10 &kp F1 &kp F2  &kp F3    &kp PAUSE_BREAK &none &none     &none     &kp RALT &none
                                &kp K_APP &kp SPACE &kp TAB       &none  &none
            >;
        };

    }; /* end keymap */
}; /* end root */
#+END_SRC

* Build

=setup.sh= drops you into a Guix shell with everything ready:

#+BEGIN_SRC sh :tangle no
cd ~/src/zmk-charybdis

# Build left half (central)
west build -s zmk/app -b nice_nano -p -- \
  -DSHIELD=charybdis_left_bt \
  -DZMK_CONFIG="$(pwd)/config" \
  -DZMK_EXTRA_MODULES="$(pwd)/zmk-pmw3610-driver"
cp build/zephyr/zmk.uf2 charybdis_left.uf2

# Build right half (peripheral)
west build -s zmk/app -b nice_nano -p -- \
  -DSHIELD=charybdis_right_bt \
  -DZMK_CONFIG="$(pwd)/config" \
  -DZMK_EXTRA_MODULES="$(pwd)/zmk-pmw3610-driver"
cp build/zephyr/zmk.uf2 charybdis_right.uf2
#+END_SRC

* Flash

The SuperMini nRF52840 uses a UF2 bootloader. To flash:

1. Connect the half via USB-C
2. Double-tap the reset button — the board mounts as a USB drive (=NICENANO=)
3. Mount with =udisksctl mount -b /dev/sda=
4. Copy the =.uf2= file to the mounted drive

#+BEGIN_SRC sh :tangle no
udisksctl mount -b /dev/sda
cp charybdis_left.uf2 /run/media/$USER/NICENANO/

# Repeat for right half
udisksctl mount -b /dev/sda
cp charybdis_right.uf2 /run/media/$USER/NICENANO/
#+END_SRC

The board unmounts and reboots automatically after the copy completes.

** Settings Reset

If Bluetooth pairing gets stuck, flash the settings reset firmware to
both halves, then re-flash the normal firmware:

#+BEGIN_SRC sh :tangle no
cd ~/src/zmk-charybdis
west build -s zmk/app -b nice_nano -p -- -DSHIELD=settings_reset
udisksctl mount -b /dev/sda
cp build/zephyr/zmk.uf2 /run/media/$USER/NICENANO/
# Repeat for each half, then re-flash charybdis_left/right.uf2
#+END_SRC

* Troubleshooting

- *Trackball not working:* Sensor is on the right (peripheral) half. Verify SPI
  pin assignments in =charybdis_right_bt.overlay= match your PCB wiring.
- *Halves not pairing:* Unplug left, wait 5s, replug. Both halves must be powered.
  If still stuck, flash =settings_reset= to both halves, then re-flash.
- *Wrong trackball axis:* Adjust =CONFIG_PMW3610_ORIENTATION_90= in =charybdis.conf=.
  Options: =_0=, =_90=, =_180=, =_270=.
- *Trackball too fast/slow:* Add to =charybdis.conf=:
  =CONFIG_PMW3610_CPI=600= (default varies, try 400-1200).
- *Build fails — Zephyr SDK:* Ensure =ZEPHYR_SDK_INSTALL_DIR= is set and the ARM
  toolchain is installed via =./setup.sh -t arm-zephyr-eabi=.
- *Right half dead after flash:* Unplug left, wait, replug — BLE split needs
  reconnection time after firmware updates.
