source = ./monitors.conf

$hypr = ~/.config/hypr
$hl = $hypr/hyprland
# Color scheme
source = $hypr/scheme/current.conf

# Variables
source = $hypr/variables.conf

# Default monitor
monitor = , preferred, auto, 1

# Configs
source = $hl/general.conf
source = $hl/input.conf
source = $hl/misc.conf
source = $hl/animations.conf
source = $hl/decoration.conf
source = $hl/group.conf
source = $hl/execs.conf
source = $hl/rules.conf
source = $hl/gestures.conf
source = $hl/keybinds.conf

# Plugins
source = $hypr/plugins.conf
