general {
	lock_cmd = loginctl lock-session
	before_sleep_cmd = loginctl lock-session
	after_sleep_cmd = hyprctl dispatch dpms on
	ignore_dbus_inhibit = false             # whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
}

listener {
	timeout = 3575
	on-timeout = notify-send "Inhibitor" "Screen Off in 15 Sec" -i "dialog-information" -c "System" -a "System Notification"
}

listener {
	timeout = 3600
	on-timeout = loginctl lock-session
	on-resume = hyprctl dispatch dpms on
}

listener {
	timeout = 3700
	on-timeout = hyprctl dispatch dpms off
	on-resume = hyprctl dispatch dpms on
}