# Apps
$terminal = alacritty
$browser = flatpak run app.zen_browser.zen
$editor = emacsclient -c
$fileExplorer = thunar

# Touchpad
$touchpadDisableTyping = true
$touchpadScrollFactor = 0.3

# Blur
$blurEnabled = true
$blurSpecialWs = false
$blurPopups = true
$blurInputMethods = true
$blurSize = 8
$blurPasses = 2
$blurXray = false

# Shadow
$shadowEnabled = true
$shadowRange = 20
$shadowRenderPower = 3
$shadowColour = rgba($surfaced4)

# Gaps
$workspaceGaps = 20
$windowGapsIn = 3
$windowGapsOut = 9
$singleWindowGapsOut = 0

# Window styling
$windowOpacity = 0.95
$windowRounding = 20

$windowBorderSize = 3
$activeWindowBorderColour = rgba($primarye6)
$inactiveWindowBorderColour = rgba($onSurfaceVariant11)

# Misc
$volumeStep = 6
$cursorTheme = Bibata-Modern-Amber
$cursorSize = 24
