#!/bin/zsh

# Starship Prompt
eval "$(starship init zsh)"

# Bash-like navigation
autoload -U select-word-style
select-word-style bash

## History file configuration
[ -z "$HISTFILE" ] && HISTFILE="${ZDOTDIR:-$HOME/.config/zsh}/history"
[ "$HISTSIZE" -lt 50000 ] && HISTSIZE=50000
[ "$SAVEHIST" -lt 10000 ] && SAVEHIST=10000

## History command configuration
setopt extended_history       # record timestamp of command in HISTFILE
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups       # ignore duplicated commands history list
setopt hist_ignore_space      # ignore commands that start with space
setopt hist_verify            # show command with history expansion to user before running it
setopt share_history          # share command history data

# Basic auto/tab complete:
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit -u
_comp_options+=(globdots)     # Include hidden files.

bindkey "^[[3~" delete-char

# Plugins sourced via mixed-text-file in home/redfish.scm

# History substring search keybinds
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Load aliases and shortcuts if existent.
[ -f "$ZDOTDIR/aliasrc" ] && source "$ZDOTDIR/aliasrc"

# Load utility functions
[ -f "$ZDOTDIR/functions" ] && source "$ZDOTDIR/functions"

# Load emacs functions
[ -f "$ZDOTDIR/emacs_functions" ] && source "$ZDOTDIR/emacs_functions"

[ -f "$(which mise)" ] && eval "$(mise activate zsh)"
