#!/bin/bash

_CURRENT_MONITOR=$(hyprctl monitors -j | jaq -r '.[] | select(.focused == true) | .name')
_OUTPUT_DIR="$HOME/Videos/ScreenRecords"
_TIMESTAP=$(date +%Y-%m-%d%H:%M:%S)
_EXT=".mkv"
_PID_FILE="/tmp/wf-recorder.pid"

# Ensure the output directory exists
mkdir -p $_OUTPUT_DIR

function start_recording() {
  wf-recorder -f ${_OUTPUT_DIR}/${_TIMESTAP}${_EXT} -o $_CURRENT_MONITOR &
  echo $! > $_PID_FILE
  echo "Recording started with PID $(cat $_PID_FILE)"
  eww update record_state=""
}

function stop_recording() {
  kill -INT $(cat $_PID_FILE)
  rm $_PID_FILE
  notify-send "Screen Recording" "Recording Stopped"
  eww update record_state=""
}

function show_status() {
  if [ -f $_PID_FILE ]; then
    echo ""
  else
    echo ""
  fi
}

case "$1" in
  start)
    start_recording
    ;;
  stop)
    if [ -f $_PID_FILE ]; then
      stop_recording
    else
      echo "No recording is currently running"
    fi
    ;;
  status)
    show_status
    ;;
  toggle)
    if [ -f $_PID_FILE ]; then
		# # so that sys menu closes
		# sleep 1
      stop_recording
    else
      start_recording
    fi
    ;;
  *)
    echo "Usage: $0 {start|stop|status|toggle}"
    exit 1
    ;;
esac
