#!/bin/bash
title=$(playerctl metadata --format '{{ title }}')
count=$(echo -n "$title" | wc -c)
if [ -z "$title" ]; then
	echo "Nothing Playing...";
else
	if [ "$count" -le 23 ]; then
		echo $title
	else
        title=${title:0:20}
		echo "$title..."
	fi
fi
