#! /bin/bash


emtask=$(emacsclient -e '(snehrbass/org-pomodoro-task)' 2> /dev/null)

if [ -z "${emtask}" ];
then
   emtask="No Active Pomodoro"
else
   emtask=$(echo $emtask | cut -d '"' -f 2)
fi

echo $emtask
