#! /bin/bash


emtime=$(emacsclient -e '(snehrbass/org-pomodoro-time)' 2> /dev/null)
if [ -z "${emtime}" ];
then
   emtime=0
else
   emtime=$(echo $emtime | cut -d '"' -f 2)
fi

bc <<< "$emtime*100/1500"
