#!/bin/bash

rm -rf "$HOME/.config/emacs/tramp"
rm -rf "$HOME/.config/emacs/etc"
rm -rf "$HOME/.config/emacs/elpa"
rm -rf "$HOME/.config/emacs/elpaca"
rm -rf "$HOME/.config/emacs/straight"
rm -rf "$HOME/.config/emacs/var"
# rm -rf "$HOME/.config/emacs/customs.el"
rm -rf "$HOME/.config/emacs/eshell"
rm -rf "$HOME/.config/emacs/org-roam.db"
rm -rf "$HOME/.config/emacs/tree-sitter"
rm -rf "$HOME/.config/emacs/persist"
rm -rf "$HOME/.config/emacs/forg-database.sqlite"
rm -rf "$HOME/.config/emacs/eln-cache"
rm -rf "$HOME/.config/emacs/auto-save-list"
rm -rf "$HOME/.config/emacs/package-quickstart.el"
rm -rf "$HOME/.config/emacs/package-quickstart.elc"
rm -rf "$HOME/.cache/org-persist"
