#! /bin/bash

alias pacman-update='sudo pacman-mirrors --geoip'

if type exa > /dev/null; then
    alias l='exa -lh --icons'
    alias ll='exa -l --icons'
    alias ls='exa --icons'
    alias la='exa -lha --icons'   #long list,show almost all,show type,human readable
    alias lr='exa -tRh --icons'   #sorted by date,recursive,show type,human readable
    alias tree='exa --tree'
    alias lt='exa --tree --icons -l'
    alias ldot='exa -ld .* --icons'
fi
alias t='tail -f'
alias -g H='| head'
alias -g T='| tail'
alias -g G='| grep'
alias -g L="| less"
alias -g M="| most"
alias -g LL="2>&1 | less"
alias -g CA="2>&1 | cat -A"
alias -g NE="2> /dev/null"
alias -g NUL="> /dev/null 2>&1"
alias -g P="2>&1| pygmentize -l pytb"
alias dud='du -d 1 -h'
alias duf='du -sh *'
alias fd='find . -type d -name'
alias ff='find . -type f -name'
alias h='history'
alias hgrep="fc -El 0 | grep"
alias p='ps -f'
alias sortnr='sort -n -r'
alias unexport='unset'
alias open='xdg-open 2>/dev/null'
alias rm='rm -I'
alias cp='cp -i'
alias mv='mv -i'
alias clock='tty-clock -c  -n -D'
alias ..='cd ..'
alias ...='cd ../../../'
alias ....='cd ../../../../'
alias .....='cd ../../../../'
