#!/bin/bash

# put in function bc it keeps getting in the way of system packages.
conda_setup () {
    __conda_setup="$('/usr/local/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
    if [ $? -eq 0 ]; then
        eval "$__conda_setup"
    else
        if [ -f "/usr/local/anaconda3/etc/profile.d/conda.sh" ]; then
            . "/usr/local/anaconda3/etc/profile.d/conda.sh"
        else
            export PATH="/usr/local/anaconda3/bin:$PATH"
        fi
    fi
    unset __conda_setup
    # <<< conda initialize <<<
}

if type swiperd > /dev/null; then
    cd () {
        builtin cd $@ && swiperd -a
    }
    sd () {
        builtin cd "$(swiperd)" && swiperd -a
    }
fi
