:PROPERTIES:
:ID:       c1c40359-16e8-4afa-87e6-4b6bcc405975
:END:
#+title: 2023-01-25

* [[id:45e497dc-cc4b-43f4-9110-1660aab320d6][AWS Pricing]]

** Problem

   [[https://aws.amazon.com/ec2/pricing/dedicated-instances/][Dedicated-Instances]] will be even more expensive due to a $2 per hour additional fee. How do we charge for this?


1) an hourly per instance usage fee
2) a dedicated per region fee (note that you pay this once per hour regardless of how many Dedicated Instances you're running).

** Assumptions & Constraints

*** Dedicated per region fee
    $2 per hour - An additional fee is charged once per hour in which at least one Dedicated Instance of any type is running in a region.

    Cost if you add this up for a month  2*24*30=1440

*** Dedicated Reserved Instance provide you with a significant discount

    AWS claim up to 75%. In reality it seems to be between 35-40%.


* Dynamic Pricing

** Problem

   We do not have a process for updating pricing of EC2 instances. Talking to Chris we had a script but when we made other changes it was removed.

   EC2 instance pricing is currently being injected directly into the database through Ansible.

** Assumptions & Constraints

   We actually want pricing to be dynamic. 



  [[https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/price-changes.html][AWS Pricing API]] - really confusing and will take some time to filter for the information we want.

  - region (us-east-2, govcloud)
  - availability zone - is the type actually available

  [[https://github.com/itchyny/gojq][gojq]] - ~jq~ written in go with a library interface should make parsing the desired information just as easy as it would be writing the parser in bash.
accounts separete from users

bill at the group level

site admin group

account billing reacurring


bill account through credit to one use for now.

need tool to see role costs.

create a billing admin, less work then a group


what frequency?
 once per day.






 is pricing acurate 
