# Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Apps
exec-once = dropbox
exec-once = ~/src/kando/out/Kando-linux-x64/kando
exec-once = flatpak run com.github.wwmm.easyeffects --gapplication-service

# Cursors
exec-once = hyprctl setcursor $cursorTheme $cursorSize

# Plugins
exec-once = hyprpm reload
