general {
    layout = dwindle

    allow_tearing = true

    gaps_workspaces = $workspaceGaps
    gaps_in = $windowGapsIn
    gaps_out = $windowGapsOut
    border_size = $windowBorderSize

    col.active_border = $activeWindowBorderColour
    col.inactive_border = $inactiveWindowBorderColour

    resize_on_border = true
    extend_border_grab_area = 10
}

dwindle {
    pseudotile = yes
    preserve_split = yes
    smart_split = no
    smart_resizing = true
}
