input {
    kb_layout = us
    follow_mouse = 2
    mouse_refocus = false
    sensitivity = 0

    repeat_delay = 250
    repeat_rate = 35

    focus_on_close = 1

    touchpad {
        natural_scroll = yes
        disable_while_typing = $touchpadDisableTyping
        scroll_factor = $touchpadScrollFactor
    }
}

binds {
    scroll_event_delay = 0
}

cursor {
    no_hardware_cursors = true
    no_warps = true
    inactive_timeout = 10
    hide_on_key_press = false
    hide_on_touch = false
    hotspot_padding = 1
}
