misc {
    vfr = true
    vrr = 2

    animate_manual_resizes = false
    animate_mouse_windowdragging = false

    disable_hyprland_logo = true
    force_default_wallpaper = 0

    focus_on_activate = true
    enable_swallow = true
    swallow_regex = ^(Alacritty)$
    close_special_on_empty = true

    allow_session_lock_restore = true
    middle_click_paste = false
    session_lock_xray = true

    mouse_move_enables_dpms = true
    key_press_enables_dpms = true

    background_color = rgb($surfaceContainer)
}

ecosystem {
    no_update_news = true
}

debug {
    error_position = 1
}
