import = ["/home/nehrbash/.config/alacritty/ef.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Beam"

[env]
TERM = "xterm-256color"

[font.bold]
family = "Iosevka"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold"

[font.italic]
family = "Iosevka"
style = "Italic"

[font.normal]
family = "Iosevka"

[scrolling]
history = 5000

[window]
decorations = "None"
dynamic_padding = true
opacity = 1.0
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 8
y = 4
