[colors.bright]
black = "0x59463f"
blue = "0x98bfff"
cyan = "0x7fc5df"
green = "0xa0d13a"
magenta = "0xfa90aa"
red = "0xff7f4f"
white = "0xa2c080"
yellow = "0xffa21f"

[colors.normal]
black = "0x352718"
blue = "0x57aff6"
cyan = "0x6fcad0"
green = "0x6fd560"
magenta = "0xf0aac5"
red = "0xff7f7f"
white = "0xe8e4b1"
yellow = "0xe4b53f"

[colors.primary]
background = "#281d12"
foreground = "#e8e4b1"
