#!/bin/bash

rm -rf "$HOME/.emacs.d/tramp"
rm -rf "$HOME/.emacs.d/etc"
rm -rf "$HOME/.emacs.d/elpa"
rm -rf "$HOME/.emacs.d/elpaca"
rm -rf "$HOME/.emacs.d/straight"
rm -rf "$HOME/.emacs.d/var"
rm -rf "$HOME/.emacs.d/customs.el"
rm -rf "$HOME/.emacs.d/eshell"
rm -rf "$HOME/.emacs.d/org-roam.db"
rm -rf "$HOME/.emacs.d/tree-sitter"
rm -rf "$HOME/.emacs.d/persist"
rm -rf "$HOME/.emacs.d/forg-database.sqlite"
rm -rf "$HOME/.emacs.d/eln-cache"
rm -rf "$HOME/.emacs.d/auto-save-list"
rm -rf "$HOME/.emacs.d/package-quickstart.el"
rm -rf "$HOME/.emacs.d/package-quickstart.elc"
